### ISSUE TITLE
Get all installed applications on a machine

### ISSUE THREAD

**Issue by wharvex** [wharvex/Armoire#7]
It would be cool if we could let the user browse through all their installed applications in order to choose items to add to a drawer or the dock.

Here are some options for this (Windows only):

[SO Post](https://stackoverflow.com/questions/908850/get-installed-applications-in-a-system)

**Comment by wharvex** [comment]
Maybe also try this

https://learn.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.findpackages?view=winrt-26100

**Comment by Bret-1** [comment]
Completed using windows start menu and drag and drop
