### ISSUE TITLE
Make paint work on Windows 10 and 11

### ISSUE THREAD

**Issue by wharvex** [wharvex/Armoire#8]
Right now it only works on Windows 10.

**Comment by Bret-1** [comment]
Added a band aid fix to check for current windows version, but it will only work for tim on windows 11

**Comment by wharvex** [comment]
It now works for anyone on Win 11 with commit [f596814](https://github.com/wharvex/Armoire/commit/f59681427c8d27834c9e4e80f530dc46c80445ed)

**Comment by Bret-1** [comment]
tim added functionality to search from the users folder if on windows 11
